name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Doctest and Minimal Tests
        run: |
          ./main.py Test_Minimal
      - name: Run variational determinant-driven tests
        run: |
          ./main.py Test1_VariationalPowerplant_Determinant
      - name: Run variational integral-driven tests
        run: |
          ./main.py Test1_VariationalPowerplant_Integral
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'

    build:

      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.9"]

      steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run doctest and unitests
          run: |
            ./main.py
